# LaminDB Instance Setup — TxGNN

**Date:** 2026-02-28  
**Instance slug:** `jkobject/txgnn_fresh2`  
**Storage:** `data/lamin_txgnn_fresh2/`

This notebook records every step taken to populate the local LaminDB instance
with bionty reference ontologies and `pertdb.Compound` records sourced from
`laminlabs/pertdata`.

## 1. Connect to the local instance

In [1]:
import lamindb as ln
import bionty as bt
import pertdb as pt
import pandas as pd

#ln.connect("jkobject/laminkg")

→ connected lamindb: jkobject/laminkg
→ doing nothing, already connected lamindb: jkobject/laminkg
→ connected lamindb: jkobject/laminkg
Connected to: jkobject/laminkg
Storage     : /Users/jkobject/Documents/code/pert-gym/laminkg

## 2. Initial instance audit

Before any imports the instance contained only **1 Organism** (human,
auto-created by lamindb) and **1,934 Gene** records left over from a previous
partial sync. Everything else was empty.

In [3]:
registries = [
    ("bt.Organism",           bt.Organism),
    ("bt.CellType",           bt.CellType),
    ("bt.Disease",            bt.Disease),
    ("bt.Tissue",             bt.Tissue),
    ("bt.Phenotype",          bt.Phenotype),
    ("bt.Pathway",            bt.Pathway),
    ("bt.Gene",               bt.Gene),
    ("bt.ExperimentalFactor", bt.ExperimentalFactor),
    ("bt.CellLine",           bt.CellLine),
    ("pt.Compound",           pt.Compound),
    ("pt.GeneticPerturbation",     pt.GeneticPerturbation),
    ("pt.EnvironmentalPerturbation", pt.EnvironmentalPerturbation),
]

for name, reg in registries:
    print(f"  {name:<35}  {reg.objects.count():>10,}")

  bt.Organism                                   0
  bt.CellType                                   0
  bt.Disease                                    0
  bt.Tissue                                     0
  bt.Phenotype                                  0
  bt.Pathway                                    0
  bt.Gene                                       0
  bt.ExperimentalFactor                         0
  bt.CellLine                                   0
  pt.Compound                                   0
  pt.GeneticPerturbation                        0
  pt.EnvironmentalPerturbation                  0

## 3. Available bionty sources

Inspect the `bt.Source` catalogue — which ontologies are registered and which
are set as `currently_used`.

In [4]:
sources_df = pd.DataFrame(
    bt.Source.objects.values(
        "entity", "name", "version", "organism", "currently_used", "in_db"
    )
).sort_values(["entity", "currently_used"], ascending=[True, False])

pd.set_option("display.max_rows", 50)
pd.set_option("display.max_colwidth", 40)
sources_df

,entity,name,version,organism,currently_used,in_db
27,BFXPipeline,lamin,1.0.0,all,True,False
33,BioSample,ncbi,2023-09,all,True,False
28,Drug,dron,2024-08-05,all,True,False
29,Drug,chebi,2024-07-27,all,False,False
13,bionty.CellLine,cellosaurus,53.0,all,True,False
14,bionty.CellLine,clo,2022-03-21,all,False,False
15,bionty.CellLine,depmap,2024-Q2,all,False,False
11,bionty.CellMarker,cellmarker,2.0,human,True,False
12,bionty.CellMarker,cellmarker,2.0,mouse,True,False
16,bionty.CellType,cl,2025-12-17,all,True,False
30,bionty.DevelopmentalStage,hsapdv,2025-01-23,human,True,False
31,bionty.DevelopmentalStage,mmusdv,2025-01-23,mouse,True,False
18,bionty.Disease,mondo,2026-01-06,all,True,False
19,bionty.Disease,doid,2025-12-23,human,True,False
20,bionty.Disease,icd,icd-11-2023,human,False,False
32,bionty.Ethnicity,hancestro,2025-10-14,human,True,False
21,bionty.ExperimentalFactor,efo,3.85.0,all,True,False
6,bionty.Gene,ensembl,release-114,human,True,False
7,bionty.Gene,ensembl,release-114,mouse,True,False
8,bionty.Gene,ensembl,release-114,saccharomyces cerevisiae,True,False
0,bionty.Organism,ensembl,release-114,vertebrates,True,False
1,bionty.Organism,ensembl,release-57,bacteria,True,False
2,bionty.Organism,ensembl,release-57,fungi,True,False
3,bionty.Organism,ensembl,release-57,metazoa,True,False
4,bionty.Organism,ensembl,release-57,plants,True,False
5,bionty.Organism,ncbitaxon,2025-12-03,all,True,False
25,bionty.Pathway,go,2025-10-10,all,True,False
26,bionty.Pathway,pw,7.96,all,False,False
22,bionty.Phenotype,pato,2025-05-14,all,True,False
23,bionty.Phenotype,hp,2026-01-08,human,True,False
24,bionty.Phenotype,phe,1.2,human,False,False
9,bionty.Protein,uniprot,2024-03,human,True,False
10,bionty.Protein,uniprot,2024-03,mouse,True,False
17,bionty.Tissue,uberon,2025-12-04,all,True,False

## 4. Public source sizes (probed before importing)

Each bionty registry exposes a `.public()` accessor backed by a versioned
Parquet file. We measured the record counts before running the bulk import.

In [5]:
probes = [
    ("bt.Organism",           bt.Organism,           None,     "ncbitaxon"),
    ("bt.CellType",           bt.CellType,           None,     "cl"),
    ("bt.Disease",            bt.Disease,            None,     "mondo"),
    ("bt.Tissue",             bt.Tissue,             None,     "uberon"),
    ("bt.Phenotype (HP)",     bt.Phenotype,          "human",  "hp"),
    ("bt.Pathway",            bt.Pathway,            None,     "go"),
    ("bt.Gene (human)",       bt.Gene,               "human",  "ensembl"),
    ("bt.ExperimentalFactor", bt.ExperimentalFactor, None,     "efo"),
    ("bt.CellLine",           bt.CellLine,           None,     "cellosaurus"),
]

rows = []
for label, reg, organism, src_name in probes:
    source = bt.Source.objects.filter(entity=reg.__name__ if hasattr(reg, '__name__') else label,
                                      name=src_name).first()
    try:
        kw = {"source": source}
        if organism:
            kw["organism"] = organism
        pub = reg.public(**kw)
        n = len(pub.df())
    except Exception as e:
        n = f"ERROR: {e}"
    rows.append({"registry": label, "source": src_name, "public_records": n})

pd.DataFrame(rows)
# Results:
# bt.Organism (ncbitaxon)   2,708,857   <- skipped (too large / not needed)
# bt.CellType (cl)              3,437
# bt.Disease  (mondo)          30,371
# bt.Tissue   (uberon)         15,770
# bt.Phenotype/HP (human)      19,934
# bt.Pathway  (go)             48,196
# bt.Gene/human (ensembl)      91,673
# bt.ExperimentalFactor (efo)  18,326
# bt.CellLine (cellosaurus)   167,126

... synchronizing df_vertebrates__ensembl__release-114__Organism.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__cl__2025-12-17__CellType.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__mondo__2026-01-06__Disease.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__uberon__2025-12-04__Tissue.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_human__hp__2026-01-08__Phenotype.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__go__2025-10-10__Pathway.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_human__ensembl__release-114__Gene.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__efo__3.85.0__ExperimentalFactor.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

... synchronizing df_all__cellosaurus__53.0__CellLine.parquet: 100.0%

/var/folders/yx/tq4qnjy56qlfjrjsdf_qtwpw0000gn/T/ipykernel_67794/3655562291.py:22: DeprecationWarning: Use to_dataframe instead of df, df will be removed in the future.
  n = len(pub.df())

                registry       source  public_records
0            bt.Organism    ncbitaxon             346
1            bt.CellType           cl            3437
2             bt.Disease        mondo           30371
3              bt.Tissue       uberon           15770
4      bt.Phenotype (HP)           hp           19934
5             bt.Pathway           go           48196
6        bt.Gene (human)      ensembl           91673
7  bt.ExperimentalFactor          efo           18326
8            bt.CellLine  cellosaurus          167126

## 5. Bulk-import bionty ontologies

`import_source()` downloads the versioned Parquet file and bulk-inserts all
records into the local SQLite database. `bt.Organism` (2.7 M NCBI taxa) was
skipped — only the single _human_ organism is needed for TxGNN.

> **Note on Phenotype**: the `currently_used` source was **PATO** (general
> quality ontology, 2 785 terms), not **HP** (Human Phenotype Ontology, 19 934
> terms). TxGNN's `effect/phenotype` nodes are 100 % HPO IDs
> (`node_source='HPO'`), so HP must be imported separately (see §7).

In [6]:
# This cell documents what was executed in reproduce/import_bionty_and_pertdb.py
# Run time: ~7 minutes total (18:40:32 → 18:47:18 local time)

REGISTRIES = [
    ("bionty.CellType",           bt.CellType,           None),
    ("bionty.Disease",            bt.Disease,            None),
    ("bionty.Tissue",             bt.Tissue,             None),
    ("bionty.Phenotype",          bt.Phenotype,          None),   # PATO — see §7
    ("bionty.Pathway",            bt.Pathway,            None),
    ("bionty.Gene",               bt.Gene,               "human"),
    ("bionty.ExperimentalFactor", bt.ExperimentalFactor, None),
    ("bionty.CellLine",           bt.CellLine,           None),
]

for entity_name, registry, organism in REGISTRIES:
    before = registry.objects.count()
    source = bt.Source.objects.filter(entity=entity_name, currently_used=True).first()
    if source is None:
        print(f"{entity_name}: no active source, skip"); continue
    kw = {"source": source, "ignore_conflicts": True}
    if organism:
        kw["organism"] = organism
    registry.import_source(**kw)
    after = registry.objects.count()
    print(f"{entity_name:<35}  {before:>8,} → {after:>8,}  (+{after-before:,})")

bionty.CellType                             0 →    3,437  (+3,437)
→ starting creation of 30371 Disease records in batches of 10000
→ starting creation of 39555 Disease_parents records in batches of 10000
bionty.Disease                              0 →   30,371  (+30,371)
→ starting creation of 15770 Tissue records in batches of 10000
→ starting creation of 42140 Tissue_parents records in batches of 10000
bionty.Tissue                               0 →   15,770  (+15,770)
... synchronizing df_all__pato__2025-05-14__Phenotype.parquet: 100.0%
bionty.Phenotype                            0 →    2,785  (+2,785)
→ starting creation of 48196 Pathway records in batches of 10000
→ starting creation of 60096 Pathway_parents records in batches of 10000
bionty.Pathway                              0 →   48,196  (+48,196)
→ starting creation of 91673 Gene records in batches of 10000
bionty.Gene                                 0 →   86,364  (+86,364)
→ starting creation of 18326 ExperimentalFactor records in batches of 10000
→ starting creation of 16430 ExperimentalFactor_parents records in batches of 10000
bionty.ExperimentalFactor                   0 →   18,326  (+18,326)
→ starting creation of 167126 CellLine records in batches of 10000
→ starting creation of 67729 CellLine_parents records in batches of 10000
bionty.CellLine                             0 →  167,126  (+167,126)

## 6. Transfer `pertdb.Compound` from `laminlabs/pertdata`

The public `laminlabs/pertdata` instance holds **24 882** curated compounds
(drugs, tool compounds, environmental perturbagens). We fetched all records as
plain Python dicts, reconnected to the local instance, and bulk-created them.

In [15]:
COMPOUND_FIELDS = (
    "uid", "name", "ontology_id", "abbr", "synonyms",
    "description", "type", "chembl_id", "smiles",
    "canonical_smiles", "inchikey", "molweight", "molformula", "moa",
)

# ── Step A: fetch from remote ──────────────────────────────────────────────
db = ln.DB("laminlabs/pertdata")
print("Remote:", ln.setup.settings.instance.slug)
total_remote = db.pertdb.Compound.filter().count()
print("Remote compounds:", total_remote)

all_compound_dicts = []
FETCH_CHUNK = 2000
for start in range(0, total_remote, FETCH_CHUNK):
    batch = list(
        db.pertdb.Compound.filter().all()[start : start + FETCH_CHUNK].values(*COMPOUND_FIELDS)
    )
    all_compound_dicts.extend(batch)
print(f"Fetched {len(all_compound_dicts):,} records")

# ── Step B: bulk-create locally ────────────────────────────────────────────
print("Local:", ln.setup.settings.instance.slug)

local_before = pt.Compound.objects.count()
existing_uids = set(pt.Compound.objects.values_list("uid", flat=True))

buffer, created_total, skipped_total = [], 0, 0
SAVE_CHUNK = 500

for d in all_compound_dicts:
    if d["uid"] in existing_uids:
        skipped_total += 1; continue
    kwargs = {k: d[k] for k in COMPOUND_FIELDS if d.get(k) is not None}
    buffer.append(pt.Compound(**kwargs))
    if len(buffer) >= SAVE_CHUNK:
        pt.Compound.objects.bulk_create(buffer, ignore_conflicts=True)
        created_total += len(buffer); buffer = []

if buffer:
    pt.Compound.objects.bulk_create(buffer, ignore_conflicts=True)
    created_total += len(buffer)

local_after = pt.Compound.objects.count()
print(f"Compounds: {local_before:,} → {local_after:,}  (+{local_after - local_before:,})")
print(f"Created: {created_total:,}  |  Skipped: {skipped_total:,}")

Remote: jkobject/laminkg
Remote compounds: 22341
Fetched 22,341 records
Local: jkobject/laminkg
! you are trying to create a record with name='ribonucleoside' but a record with similar name exists: '2'-deoxyribonucleoside'. Did you mean to load it?
! you are trying to create a record with name='deoxyribonucleoside' but a record with similar name exists: '2'-deoxyribonucleoside'. Did you mean to load it?
! you are trying to create a record with name='diazole' but a record with similar name exists: 'thiadiazoles'. Did you mean to load it?
! you are trying to create a record with name='flavones' but a record with similar name exists: 'biflavonoid'. Did you mean to load it?
! you are trying to create a record with name='furans' but a record with similar name exists: 'Cytosine-1-beta-D-arabinofuranoside hydrochloride'. Did you mean to load it?
! you are trying to create a record with name='hydroxamic acid' but a record with similar name exists: 'hydroxamic acid ester'. Did you mean to load it?
! you are trying to create a record with name='imidazoles' but a record with similar name exists: 'benzimidazoles'. Did you mean to load it?
! you are trying to create a record with name='lactam' but records with similar names exist: 'lactone', 'delta-lactone'. Did you mean to load one of them?
! you are trying to create a record with name='monoterpenoid' but a record with similar name exists: 'monoterpenoid indole alkaloid'. Did you mean to load it?
! you are trying to create a record with name='oxide' but records with similar names exist: 'organic oxide', 'hydroxides'. Did you mean to load one of them?
! you are trying to create a record with name='pterins' but a record with similar name exists: 'pteridines'. Did you mean to load it?
! you are trying to create a record with name='pyrazoles' but a record with similar name exists: 'pyrazolopyrimidine'. Did you mean to load it?
! you are trying to create a record with name='tetracyclines' but records with similar names exist: 'tetracyclic diterpenoid', 'organic heterotetracyclic compound'. Did you mean to load one of them?
! you are trying to create a record with name='nucleoside' but a record with similar name exists: '2'-deoxyribonucleoside'. Did you mean to load it?
! you are trying to create a record with name='oxazole' but records with similar names exist: 'benzoxazole', '1,3-benzoxazoles'. Did you mean to load one of them?
! you are trying to create a record with name='pyridone' but records with similar names exist: 'pyridopyrimidine', 'Pyridostatin hydrochloride'. Did you mean to load one of them?
! you are trying to create a record with name='pyrimidines' but records with similar names exist: 'pyrazolopyrimidine', 'pyrrolopyrimidine', 'pyridopyrimidine'. Did you mean to load one of them?
! you are trying to create a record with name='flavonoid' but a record with similar name exists: 'biflavonoid'. Did you mean to load it?
! you are trying to create a record with name='acetal' but records with similar names exist: 'acetohydroxamic-acid', 'acetate ester', 'Guanabenz acetate'. Did you mean to load one of them?
! you are trying to create a record with name='flavonoids' but a record with similar name exists: 'biflavonoid'. Did you mean to load it?
! you are trying to create a record with name='benzopyran' but records with similar names exist: 'benzopyrrole', 'dibenzopyrrole'. Did you mean to load one of them?
! you are trying to create a record with name='pyrroles' but records with similar names exist: 'pyrrolidines', 'pyrrolopyrimidine', 'pyrrolidinecarboxamide'. Did you mean to load one of them?
! you are trying to create a record with name='dicarboxylic acid' but records with similar names exist: 'dicarboxylic acids and O-substituted derivatives', 'dicarboxylic acid monoester'. Did you mean to load one of them?
! you are trying to create a record with name='quinone' but records with similar names exist: 'quinolines', 'clioquinol', 'pyranoindolizinoquinoline'. Did you mean to load one of them?
! you are trying to create a record with name='beta-D-arabinoside' but a record with similar name exists: 'Cytosine-1-beta-D-arabinofuranoside hydrochloride'. Did you mean to load it?
! you are trying to create a record with name='enamide' but a record with similar name exists: 'mefenamic-acid'. Did you mean to load it?
! you are trying to create a record with name='delta-lactam' but a record with similar name exists: 'delta-lactone'. Did you mean to load it?
! you are trying to create a record with name='adenine' but a record with similar name exists: 'erythro-9-(2-Hydroxy-3-nonyl)adenine hydrochloride'. Did you mean to load it?
! you are trying to create a record with name='anilide' but records with similar names exist: 'anilines', 'substituted aniline'. Did you mean to load one of them?
! you are trying to create a record with name='glycol' but a record with similar name exists: 'glycine derivative'. Did you mean to load it?
! you are trying to create a record with name='ferulic acid' but a record with similar name exists: 'ferulic acids'. Did you mean to load it?
! you are trying to create a record with name='dicarboxylic acid amide' but records with similar names exist: 'dicarboxylic acid monoester', 'dicarboxylic acids and O-substituted derivatives'. Did you mean to load one of them?
! you are trying to create a record with name='ethyl ester' but a record with similar name exists: 'methyl ester'. Did you mean to load it?
! you are trying to create a record with name='uridines' but a record with similar name exists: 'Idoxuridine'. Did you mean to load it?
! you are trying to create a record with name='secondary amine' but records with similar names exist: 'secondary amide', 'secondary amino compound'. Did you mean to load one of them?
! you are trying to create a record with name='amine' but records with similar names exist: 'aromatic amine', '5-methoxytryptamine', 'amthamine'. Did you mean to load one of them?
! you are trying to create a record with name='sulfone' but records with similar names exist: 'sulfonamide', 'sulfonic acid derivative', 'N-sulfonylcarboxamide'. Did you mean to load one of them?
! you are trying to create a record with name='triazines' but a record with similar name exists: 'benzotriazines'. Did you mean to load it?
! you are trying to create a record with name='cardenolides' but a record with similar name exists: 'cardenolide glycoside'. Did you mean to load it?
! you are trying to create a record with name='DMSO_TF' but a record with similar name exists: 'Trametinib (DMSO_TF solvate)'. Did you mean to load it?
! you are trying to create a record with name='dapagliflozin' but a record with similar name exists: 'Dapagliflozin ((2S)-1,2-propanediol, hydrate)'. Did you mean to load it?
! you are trying to create a record with name='uridine' but records with similar names exist: 'uridines', 'Idoxuridine', 'trifluridine'. Did you mean to load one of them?
! you are trying to create a record with name='folic acid' but a record with similar name exists: 'folic acids'. Did you mean to load it?
! you are trying to create a record with name='gallic acid' but a record with similar name exists: 'Gallic acid (hydrate)'. Did you mean to load it?
! you are trying to create a record with name='xanthinol' but a record with similar name exists: 'anthoxanthin'. Did you mean to load it?
! you are trying to create a record with name='EMF-sumo1-9' but a record with similar name exists: 'EMF-sumo1-8'. Did you mean to load it?
! you are trying to create a record with name='L-alpha-amino acid' but a record with similar name exists: 'N-acyl-L-alpha-amino acid'. Did you mean to load it?
! you are trying to create a record with name='vinblastine' but a record with similar name exists: 'Vinblastine (sulfate)'. Did you mean to load it?
! you are trying to create a record with name='sterol' but records with similar names exist: 'steroid', 'sterol ester', 'steroid ester'. Did you mean to load one of them?
! you are trying to create a record with name='NECA' but records with similar names exist: 'arenecarboxamide', 'pyrrolidinecarboxamide', 'piperidinecarboxamide'. Did you mean to load one of them?
! you are trying to create a record with name='BL-077' but a record with similar name exists: 'BL-074'. Did you mean to load it?
! you are trying to create a record with name='CVF-SUMO-11' but records with similar names exist: 'CVF-SUMO-13', 'CVF-SUMO-7'. Did you mean to load one of them?
! you are trying to create a record with name='BG-1008' but a record with similar name exists: 'BG-1015'. Did you mean to load it?
! you are trying to create a record with name='cortisone-acetate' but a record with similar name exists: 'fludrocortisone-acetate'. Did you mean to load it?
! you are trying to create a record with name='H-7' but a record with similar name exists: 'PH-797804'. Did you mean to load it?
! you are trying to create a record with name='epirubicin' but a record with similar name exists: 'Epirubicin (hydrochloride)'. Did you mean to load it?
! you are trying to create a record with name='chlorcyclizine' but a record with similar name exists: 'homochlorcyclizine'. Did you mean to load it?
! you are trying to create a record with name='norcitalopram' but a record with similar name exists: 'dinorcitalopram-oxalate'. Did you mean to load it?
! you are trying to create a record with name='ST-019386' but a record with similar name exists: 'ST-019366'. Did you mean to load it?
! you are trying to create a record with name='EMF-sumo1-6' but records with similar names exist: 'EMF-sumo1-8', 'EMF-sumo1-9'. Did you mean to load one of them?
! you are trying to create a record with name='gemcitabine' but a record with similar name exists: 'Gemcitabine hydrochloride'. Did you mean to load it?
! you are trying to create a record with name='DAC-009' but a record with similar name exists: 'FL-HDAC-025'. Did you mean to load it?
! you are trying to create a record with name='K784-3188' but a record with similar name exists: 'K784-3187'. Did you mean to load it?
! you are trying to create a record with name='hydrocortisone' but records with similar names exist: 'hydrocortisone-hemisuccinate', 'hydrocortisone-valerate', 'hydrocortisone-phosphate'. Did you mean to load one of them?
! you are trying to create a record with name='BG-1010' but a record with similar name exists: 'BG-1015'. Did you mean to load it?
! you are trying to create a record with name='K784-3131' but a record with similar name exists: 'K784-3187'. Did you mean to load it?
! you are trying to create a record with name='EMF-sumo1-11' but records with similar names exist: 'EMF-sumo1-8', 'EMF-sumo1-9'. Did you mean to load one of them?
! you are trying to create a record with name='EMF-sumo1-10' but records with similar names exist: 'EMF-sumo1-8', 'EMF-sumo1-9'. Did you mean to load one of them?
! you are trying to create a record with name='EMF-sumo1-39' but records with similar names exist: 'EMF-sumo1-8', 'EMF-sumo1-9'. Did you mean to load one of them?
! you are trying to create a record with name='carbohydrate' but records with similar names exist: 'carbohydrazide', 'carbohydrate derivative', 'carbohydrate acid derivative'. Did you mean to load one of them?
! you are trying to create a record with name='glycan' but records with similar names exist: 'glycoside', 'glycosyloxyflavone', 'glycol'. Did you mean to load one of them?
! you are trying to create a record with name='aldehyde' but a record with similar name exists: 'steroid aldehyde'. Did you mean to load it?
! you are trying to create a record with name='vitamin B2' but records with similar names exist: 'vitamin B9', 'vitamin B6', 'vitamin K'. Did you mean to load one of them?
! you are trying to create a record with name='vitamin B3' but records with similar names exist: 'vitamin B9', 'vitamin B6', 'vitamin K'. Did you mean to load one of them?
! you are trying to create a record with name='vitamin B7' but records with similar names exist: 'vitamin B9', 'vitamin B6', 'vitamin K'. Did you mean to load one of them?
! you are trying to create a record with name='benzenediol' but a record with similar name exists: 'benzenediols'. Did you mean to load it?
! you are trying to create a record with name='sulfoxide' but records with similar names exist: 'l-buthionine-sulfoximine', 'buthionine-sulfoximine'. Did you mean to load one of them?
! you are trying to create a record with name='acetamides' but a record with similar name exists: 'N-(3-acetamidophenyl)-3-chlorobenzamide'. Did you mean to load it?
! you are trying to create a record with name='azide' but records with similar names exist: 'hydrazide', 'carbohydrazide', 'Balsalazide (sodium hydrate)'. Did you mean to load one of them?
! you are trying to create a record with name='benzoquinones' but records with similar names exist: '1,4-benzoquinones', 'dihydroxy-1,4-benzoquinones'. Did you mean to load one of them?
! you are trying to create a record with name='chromanes' but a record with similar name exists: 'thiochromane'. Did you mean to load it?
! you are trying to create a record with name='chromenes' but a record with similar name exists: 'chromenochromene'. Did you mean to load it?
! you are trying to create a record with name='chromones' but a record with similar name exists: 'furanochromone'. Did you mean to load it?
! you are trying to create a record with name='cyclopentanols' but a record with similar name exists: 'cyclopentanes'. Did you mean to load it?
! you are trying to create a record with name='diamine' but a record with similar name exists: 'dicarboxylic acid diamide'. Did you mean to load it?
! you are trying to create a record with name='ethanolamines' but records with similar names exist: 'palmitoylethanolamide', 'N-acylethanolamine 20:4', 'N-(long-chain-acyl)ethanolamine'. Did you mean to load one of them?
! you are trying to create a record with name='glucoside' but records with similar names exist: 'glucosiduronic acid', 'rhamnosylglucoside'. Did you mean to load one of them?
! you are trying to create a record with name='group' but records with similar names exist: 'main group molecular entity', 'boron group molecular entity', 'carbon group molecular entity'. Did you mean to load one of them?
! you are trying to create a record with name='guanidines' but records with similar names exist: 'aminoguanidine', '5'-guanidinonaltrindole'. Did you mean to load one of them?
! you are trying to create a record with name='salt' but records with similar names exist: 'Brequinar sodium salt hydrate', 'L-Thyroxine (sodium salt pentahydrate)', 'LY-2584702 (tosylate salt)'. Did you mean to load one of them?
! you are trying to create a record with name='organic salt' but a record with similar name exists: 'organic sulfide'. Did you mean to load it?
! you are trying to create a record with name='ion' but records with similar names exist: 'coordination entity', 'transition element molecular entity', 'transition element coordination entity'. Did you mean to load one of them?
! you are trying to create a record with name='methoxyflavone' but records with similar names exist: 'methoxyflavanone', '4'-methoxyflavanones', 'monomethoxyflavanone'. Did you mean to load one of them?
! you are trying to create a record with name='monomethoxyflavone' but a record with similar name exists: 'monomethoxyflavanone'. Did you mean to load it?
! you are trying to create a record with name='organic ion' but records with similar names exist: 'organic polycyclic compound', 'organic oxide', 'organic sulfide'. Did you mean to load one of them?
! you are trying to create a record with name='organic sulfate' but a record with similar name exists: 'organic sulfide'. Did you mean to load it?
! you are trying to create a record with name='oxime' but records with similar names exist: 'oxime O-ether', '5-methoxyvalerophenone O-(2-aminoethyl)oxime'. Did you mean to load one of them?
! you are trying to create a record with name='phenanthrenes' but a record with similar name exists: '6-methoxy-11-methyl-1,3,4,9,10,10a-hexahydro-2H-10,4a-(epiminoethano)phenanthrene'. Did you mean to load it?
! you are trying to create a record with name='phosphate' but records with similar names exist: 'Rucaparib (phosphate)', 'Benproperine (phosphate)', 'geranyl-geranyl-pyrophosphate'. Did you mean to load one of them?
! you are trying to create a record with name='prenols' but records with similar names exist: 'isoprenoid', 'oxprenolol'. Did you mean to load one of them?
! you are trying to create a record with name='propanediol' but a record with similar name exists: 'Dapagliflozin ((2S)-1,2-propanediol, hydrate)'. Did you mean to load it?
! you are trying to create a record with name='amidine' but a record with similar name exists: 'Pentamidine (isethionate)'. Did you mean to load it?
! you are trying to create a record with name='prostaglandins F' but a record with similar name exists: '15-delta-prostaglandin-j2'. Did you mean to load it?
! you are trying to create a record with name='purine nucleotide' but records with similar names exist: 'purine nucleobase', 'purine nucleoside', '3',5'-cyclic purine nucleotide'. Did you mean to load one of them?
! you are trying to create a record with name='pyrans' but records with similar names exist: 'pyrazines', 'pyrazolopyrimidine', 'pyranoindolizinoquinoline'. Did you mean to load one of them?
! you are trying to create a record with name='pyridazinone' but a record with similar name exists: 'imidazopyridazine'. Did you mean to load it?
! you are trying to create a record with name='quinoline alkaloid' but records with similar names exist: 'bisbenzylisoquinoline alkaloid', 'benzylisoquinoline alkaloid', 'isoquinoline alkaloid'. Did you mean to load one of them?
! you are trying to create a record with name='saponin' but a record with similar name exists: 'timosaponin'. Did you mean to load it?
! you are trying to create a record with name='sodium salt' but records with similar names exist: 'Sodium salicylate', 'Brequinar sodium salt hydrate', 'L-Thyroxine (sodium salt pentahydrate)'. Did you mean to load one of them?
! you are trying to create a record with name='sphingolipid' but a record with similar name exists: 'glycosphingolipid'. Did you mean to load it?
! you are trying to create a record with name='sulfates' but records with similar names exist: 'Sulfatinib', 'Larotrectinib sulfate', 'Estrone sulfate (potassium)'. Did you mean to load one of them?
! you are trying to create a record with name='terpene alkaloid' but a record with similar name exists: 'diterpene alkaloid'. Did you mean to load it?
! you are trying to create a record with name='toluenes' but a record with similar name exists: 'aminotoluene'. Did you mean to load it?
! you are trying to create a record with name='triol' but a record with similar name exists: 'benzenetriol'. Did you mean to load it?
! you are trying to create a record with name='tryptamines' but records with similar names exist: '5-methoxytryptamine', '5-methoxy-alpha-methyltryptamine'. Did you mean to load one of them?
! you are trying to create a record with name='tyramines' but a record with similar name exists: 'methyltyramine'. Did you mean to load it?
! you are trying to create a record with name='vitamin D' but records with similar names exist: 'vitamin B9', 'vitamin B6', 'vitamin K'. Did you mean to load one of them?
! you are trying to create a record with name='flavonols' but records with similar names exist: 'flavonoid', 'flavonoids', 'biflavonoid'. Did you mean to load one of them?
! you are trying to create a record with name='fatty amide' but a record with similar name exists: 'primary fatty amide'. Did you mean to load it?
! you are trying to create a record with name='flavin' but records with similar names exist: 'flavones', 'flavonoid', 'flavonoids'. Did you mean to load one of them?

## 7. Phenotype source: PATO vs HP

### Why PATO is the wrong choice for TxGNN

| Ontology                                | Purpose                                                                | Terms   | TxGNN relevance                                                                |
| --------------------------------------- | ---------------------------------------------------------------------- | ------- | ------------------------------------------------------------------------------ |
| **PATO** (Phenotype and Trait Ontology) | Abstract _quality_ descriptions — "increased", "decreased", "abnormal" | ~2 785  | **None** — TxGNN nodes do not use PATO IDs                                     |
| **HP** (Human Phenotype Ontology)       | Specific _human disease phenotypes_ — "Renal cyst", "Seizure"          | ~19 934 | **All 15 311** `effect/phenotype` nodes in `nodes.tab` are `node_source='HPO'` |

PATO and HP are **not directly mappable**. PATO supplies the _quality dimension_
(e.g., "PATO:0000462 absent") in the EQ (Entity–Quality) framework used to
_compose_ HPO term definitions internally. There is no reliable table of PATO_ID
→ HP_ID because:

- One PATO term can contribute to thousands of HP terms ("abnormal" alone
  underpins most of HPO)
- The relation is many-to-many and ontologically compositional, not a simple
  join

### Fix: switch `currently_used` to HP and import

```python
# Swap currently_used
pato_src = bt.Source.objects.filter(entity="bionty.Phenotype", name="pato").first()
pato_src.currently_used = False; pato_src.save()

hp_src = bt.Source.objects.filter(entity="bionty.Phenotype", name="hp").first()
hp_src.currently_used = True; hp_src.save()

# Import HP terms
bt.Phenotype.import_source(source=hp_src, organism="human", ignore_conflicts=True)
print("HP Phenotype count:", bt.Phenotype.objects.count())
```

In [17]:
# Verify TxGNN phenotype nodes all use HPO IDs
nodes = pd.read_csv("../data/txdata/nodes.tab", sep="\t")
pheno = nodes[nodes["node_type"] == "effect/phenotype"]

print(f"effect/phenotype nodes : {len(pheno):,}")
print(f"Sources                : {pheno['node_source'].value_counts().to_dict()}")
print()
print("Sample node_ids (numeric) → HP:XXXXXXX after zero-padding:")
for _, row in pheno.head(5).iterrows():
    nid = str(int(float(row['node_id']))).zfill(7)
    print(f"  node_id={row['node_id']!r}  → HP:{nid}  name={row['node_name']!r}")

effect/phenotype nodes : 15,311
Sources                : {'HPO': 15311}

Sample node_ids (numeric) → HP:XXXXXXX after zero-padding:
  node_id='1507'  → HP:0001507  name='Growth abnormality'
  node_id='107'  → HP:0000107  name='Renal cyst'
  node_id='1'  → HP:0000001  name='All'
  node_id='5'  → HP:0000005  name='Mode of inheritance'
  node_id='10460'  → HP:0010460  name='Abnormality of the female genitalia'

## 8. Final record counts after all imports

In [18]:
final = []
for name, reg in [
    ("bt.Organism",               bt.Organism),
    ("bt.CellType",               bt.CellType),
    ("bt.Disease",                bt.Disease),
    ("bt.Tissue",                 bt.Tissue),
    ("bt.Phenotype (PATO)",       bt.Phenotype),
    ("bt.Pathway",                bt.Pathway),
    ("bt.Gene",                   bt.Gene),
    ("bt.ExperimentalFactor",     bt.ExperimentalFactor),
    ("bt.CellLine",               bt.CellLine),
    ("pt.Compound",               pt.Compound),
]:
    final.append({"registry": name, "records": reg.objects.count()})

pd.DataFrame(final).set_index("registry")
# Note: bt.Phenotype will jump from 2,785 → ~22,719 once HP is imported (§7)

                       records
registry
bt.Organism                  1
bt.CellType               3437
bt.Disease               30371
bt.Tissue                15770
bt.Phenotype (PATO)       2785
bt.Pathway               48196
bt.Gene                  86364
bt.ExperimentalFactor    18326
bt.CellLine             167126
pt.Compound              22341

## 9. Recommended next steps

1. **Fix Phenotype source** — run the code in §7 to swap PATO → HP and import 19
   934 HP terms. Without this, `sync_txgnn_nodes_to_lamindb.py` will mark all
   `effect/phenotype` nodes as `uncertain`.

2. **Run the node-entity sync** — `reproduce/sync_nodes_to_lamindb.py` maps
   every node in `nodes.tab` to a local registry record.

3. **Index OpenTargets data** — 47 datasets downloaded to `data/opentargets/`
   (release 25.12) can be registered as LaminDB `Artifact` objects for lineage
   tracking.